### ISSUE TITLE
About-Me page

### ISSUE THREAD

**Issue by suryaaa-g** [Motivation-Co/motivation-co#2]
Make an about-me page to all pages

**Comment by rzmk** [comment]
To add an About page, the following would be minimally required:

- Creating about.html and about-style.css files
- Adding an About page navigation link to every page
- Making the About page's navigation link highlighted when on the About page

Try to follow the current theme and colors too.

**Comment by yashss1** [comment]
Hi @rzmk  I would like to contribute to this work.

**Comment by rzmk** [comment]
About-me page layout has been created thanks to @yashss1. 👍 Now @farhaan00 and @dhruvpatel768 will pair-program the content of this page. Ideally we would like to see:
- Each of the five Motivation Co.'s founders' with one image that describes them, their name, and a simple description about their role and goal with Motivation Co.
Of course this is while following the similar theme and color palette we have from the home page.

**Comment by rzmk** [comment]
Created the About Me page with @farhaan00 and @dhruvpatel768 in #8!
Up next is making it responsive for other devices #10.
