### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by rzmk** [Motivation-Co/motivation-co#3]
Ideally display email and social media handles/images that link to social media, and/or a contact form.

**Comment by yashss1** [comment]
Hi @rzmk, I would like to work on the issue. As i am new to the community it will be a great opportunity for me.

**Comment by rzmk** [comment]
Thanks @yashss1, however this page will have some details that we haven't set up yet which @farhaan00 and @dhruvpatel768 will setup instead.
I am assigning this issue to @farhaan00 and @dhruvpatel768 to make it easier to pass social media information for making the content of the page.

**Comment by rzmk** [comment]
Created the Contact page with @farhaan00 and @dhruvpatel768 in #8!
Up next is making it responsive for other devices #10.
