### ISSUE TITLE
Blog page-User Experience

### ISSUE THREAD

**Issue by rsarder** [Motivation-Co/motivation-co#6]
Images on blog page are too big,  make smaller so client won't have to scroll so much just to see a single post. Ideally, an entire post will fit within a screen with enough space for a caption/comments/post information

**Comment by rzmk** [comment]
I agree! 👍
The blog page **layout** was made so far, and @suryaaa-g will focus on refining/reformatting the blog page **UX** for this issue.

**Comment by rzmk** [comment]
Blog scratched in 9d26bed5692d5db3c1a26fa134bd972839657f79. Closing issue unless further progress is made on creating a blog in the future.
